Repository javascript-tutorial/cs.javascript.info, pull requests merged in 2022-05, with the labels that each got.

#68 2.3
  1-js/02-first-steps/03-strict-mode/article.md
Labels: changes requested

#70 1.2.5
  1-js/02-first-steps/05-types/1-string-quotes/solution.md
  1-js/02-first-steps/05-types/1-string-quotes/task.md
  1-js/02-first-steps/05-types/article.md
Labels: changes requested

#73 1.2.7
  1-js/02-first-steps/07-type-conversions/article.md
Labels: changes requested

#85 Revert "2.3"
  1-js/02-first-steps/03-strict-mode/article.md
Labels: review needed

#86 Revert "1.2.5"
  1-js/02-first-steps/05-types/1-string-quotes/solution.md
  1-js/02-first-steps/05-types/1-string-quotes/task.md
  1-js/02-first-steps/05-types/article.md
Labels: review needed

#87 Revert "1.2.7"
  1-js/02-first-steps/07-type-conversions/article.md
Labels: review needed

#88 Revert "Revert "2.3""
  1-js/02-first-steps/03-strict-mode/article.md
Labels: review needed

#89 Revert "Revert "1.2.5""
  1-js/02-first-steps/05-types/1-string-quotes/solution.md
  1-js/02-first-steps/05-types/1-string-quotes/task.md
  1-js/02-first-steps/05-types/article.md
Labels: review needed

#90 Revert "Revert "1.2.7""
  1-js/02-first-steps/07-type-conversions/article.md
Labels: review needed

#72 Interaction: alert, prompt, confirm
  1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/solution.md
  1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/task.md
  1-js/02-first-steps/06-alert-prompt-confirm/article.md
Labels: needs +1

#71 Variables
  1-js/02-first-steps/04-variables/1-hello-variables/solution.md
  1-js/02-first-steps/04-variables/1-hello-variables/task.md
  1-js/02-first-steps/04-variables/2-declare-variables/solution.md
  1-js/02-first-steps/04-variables/2-declare-variables/task.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/solution.md
  1-js/02-first-steps/04-variables/3-uppercast-constant/task.md
  1-js/02-first-steps/04-variables/article.md
  1-js/02-first-steps/04-variables/variable-change.svg
  1-js/02-first-steps/04-variables/variable.svg
Labels: changes requested

#74 Basic operators, maths
  1-js/02-first-steps/08-operators/1-increment-order/solution.md
  1-js/02-first-steps/08-operators/1-increment-order/task.md
  1-js/02-first-steps/08-operators/2-assignment-result/solution.md
  1-js/02-first-steps/08-operators/2-assignment-result/task.md
  1-js/02-first-steps/08-operators/3-primitive-conversions-questions/solution.md
  1-js/02-first-steps/08-operators/3-primitive-conversions-questions/task.md
  1-js/02-first-steps/08-operators/4-fix-prompt/solution.md
  1-js/02-first-steps/08-operators/4-fix-prompt/task.md
  1-js/02-first-steps/08-operators/article.md
Labels: review needed

#75 Comparisons
  1-js/02-first-steps/09-comparison/1-comparison-questions/solution.md
  1-js/02-first-steps/09-comparison/1-comparison-questions/task.md
  1-js/02-first-steps/09-comparison/article.md
Labels: review needed
